/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.telas;

/**
 *
 * @author alunolages
 */
public class PanelNovoLeilao extends javax.swing.JPanel {

    /**
     * Creates new form PanelNovoLeilao
     */
    public PanelNovoLeilao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jl_nomeItem = new javax.swing.JLabel();
        jl_valorItem = new javax.swing.JLabel();
        jl_valorIncremento = new javax.swing.JLabel();
        jb_criarLeilao = new javax.swing.JButton();
        jb_cancelar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("GOST Common", 1, 36)); // NOI18N
        jLabel1.setText("Novo Leilão");

        jLabel2.setFont(new java.awt.Font("GOST Common", 0, 18)); // NOI18N
        jLabel2.setText("Nome Item:");

        jLabel3.setFont(new java.awt.Font("GOST Common", 0, 18)); // NOI18N
        jLabel3.setText("Valor Item:");

        jLabel4.setFont(new java.awt.Font("GOST Common", 0, 18)); // NOI18N
        jLabel4.setText("Valor do Incremento:");

        jl_nomeItem.setFont(new java.awt.Font("GOST Common", 0, 18)); // NOI18N
        jl_nomeItem.setText("jLabel5");

        jl_valorItem.setFont(new java.awt.Font("GOST Common", 0, 18)); // NOI18N
        jl_valorItem.setText("jLabel6");

        jl_valorIncremento.setFont(new java.awt.Font("GOST Common", 0, 18)); // NOI18N
        jl_valorIncremento.setText("jLabel7");

        jb_criarLeilao.setFont(new java.awt.Font("GOST Common", 0, 24)); // NOI18N
        jb_criarLeilao.setText("Criar Leilão");

        jb_cancelar.setFont(new java.awt.Font("GOST Common", 0, 14)); // NOI18N
        jb_cancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jl_nomeItem))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jl_valorItem))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jl_valorIncremento))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jb_criarLeilao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jb_cancelar)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jl_nomeItem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jl_valorItem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jl_valorIncremento))
                .addGap(27, 27, 27)
                .addComponent(jb_criarLeilao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_cancelar)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jb_cancelar;
    private javax.swing.JButton jb_criarLeilao;
    private javax.swing.JLabel jl_nomeItem;
    private javax.swing.JLabel jl_valorIncremento;
    private javax.swing.JLabel jl_valorItem;
    // End of variables declaration//GEN-END:variables
}
